connection: &connection
connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: dszromik
  password: dszromik

development:
  <<: *connection
  database: give_me_food_development

test: &test
  <<: *connection
  database: give_me_food_test
